apiVersion: v1
kind: Service
metadata:
  name: cicd-lab
  labels:
    app: cicd-lab
spec:
  ports:
    - port: 8888
      protocol: TCP
      targetPort: 8888
    - name: web
      port: 8888
      targetPort: 8888
  selector:
    app: cicd-lab
  type: ClusterIP